grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
/**
 * Copyright (c) 2012 Partners In Health.  All rights reserved.
 * The use and distribution terms for this software are covered by the
 * Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
 * which can be found in the file epl-v10.html at the root of this distribution.
 * By using this software in any fashion, you are agreeing to be bound by
 * the terms of this license.
 * You must not remove this notice, or any other, from this software.
 * */
package org.pih.warehouse.reporting

import grails.converters.JSON
import groovy.time.TimeCategory
import org.apache.commons.codec.digest.DigestUtils
import org.apache.commons.collections.FactoryUtils
import org.apache.commons.collections.list.LazyList
import org.codehaus.groovy.grails.commons.DefaultGrailsDomainClass
import org.pih.warehouse.core.Constants
import org.pih.warehouse.core.Location
import org.pih.warehouse.core.Tag
import org.pih.warehouse.core.UserService
import org.pih.warehouse.inventory.InventoryLevel
import org.pih.warehouse.inventory.InventoryService
import org.pih.warehouse.inventory.Transaction
import org.pih.warehouse.inventory.TransactionCode
import org.pih.warehouse.inventory.TransactionEntry
import org.pih.warehouse.inventory.TransactionType
import org.pih.warehouse.order.OrderTypeCode
import org.pih.warehouse.product.Category
import org.pih.warehouse.product.Product
import org.pih.warehouse.product.ProductService
import org.pih.warehouse.report.ConsumptionService
import org.pih.warehouse.report.ReportService
import org.pih.warehouse.requisition.Requisition

class ConsumptionController {

    def dataService
    ReportService reportService
    ProductService productService
    InventoryService inventoryService
    ConsumptionService consumptionService
    UserService userService
    def productAvailabilityService

    def show = { ShowConsumptionCommand command ->

        if (command.hasErrors()) {
            render(view: "show", model: [command: command])
            return
        }

        String[] defaultTransactionTypeIds = [
                Constants.TRANSFER_OUT_TRANSACTION_TYPE_ID,
                Constants.CONSUMPTION_TRANSACTION_TYPE_ID
        ]

        command.defaultTransactionTypes = defaultTransactionTypeIds.collect {TransactionType.get(it)}
        command.selectedTransactionTypes = command.defaultTransactionTypes
        command.transactionTypes = command.defaultTransactionTypes

        // If any parameters have changed we need to reset filters
        if (command.parametersHash && command.hasParameterChanged()) {
            command.selectedProperties = []
            command.selectedTags = []
            command.selectedLocations = []
            command.selectedCategories = []

            if (params.format == "csv") {
                params.remove("format")
                flash.message = "Unable to download CSV as parameters have changed. Please try download again."
            }
        }


        // Hack to fix PIMS-2728
        if (command.selectedProperties) {
            if (command.selectedProperties instanceof java.lang.String) {
                command.selectedProperties = [command.selectedProperties]
            }
        }

        def tags = command.selectedTags.collect { it.tag }.asList()
        def products = tags ? inventoryService.getProductsByTags(tags) : null

        // Add an entire day to account for the 24 hour period on the end date
        Date toDate = command.toDate ? command.toDate + 1 : null

        // Set to midnight
        if (toDate) {
            toDate.clearTime()
        }

        // Get all transactions
        command.debits = inventoryService.getDebitsBetweenDates(command.fromLocations,
                command.selectedLocations, command.fromDate, toDate,
                command.selectedTransactionTypes)
        // Get credits for INBOUND RETURNS, selectedLocations = sources, fromLocation = destination inventory
        command.credits = inventoryService.getCreditsBetweenDates(command.selectedLocations, command.fromLocations, command.fromDate, toDate)

        def transactions = []
        transactions.addAll(command.debits)
        transactions.addAll(command.credits?.findAll { it.incomingShipment?.isFromReturnOrder })

        // Sort transaction by date ascending
        transactions = transactions.sort { it.transactionDate }

        // Used within the transaction block to see if we need to add all destinations to command.toLocations
        // which occurs if there are no toLocations selected
        boolean toLocationsEmpty = command.toLocations.empty
        boolean fromLocationsEmpty = command.fromLocations.empty

        // Some transactions don't have a destination (e.g. expired, consumed, etc)
        if (toLocationsEmpty) {
            def debitLocations = transactions.findAll { it.destination != null }.collect {
                it.destination
            }
            def creditLocations = transactions.findAll { it.source != null && it.incomingShipment?.isFromReturnOrder }.collect {
                it.source
            }
            command.toLocations.addAll(debitLocations)
            command.toLocations.addAll(creditLocations)
        }

        // Keep track of all the transaction types (we may want to select a subset of these)
        // FIXME Hard-code transaction types (OBPIH-2059)
        command.transactionTypes = transactions*.transactionType.unique()

        def userHasFinanceRole = userService.hasRoleFinance(session?.user)

        // Iterate over all transactions
        transactions.each { Transaction transaction ->

            // Iterate over all transaction entries
            transaction.transactionEntries.each { TransactionEntry transactionEntry ->
                def product = transactionEntry.inventoryItem.product
                def currentRow = command.rows[product]
                if (!currentRow) {
                    command.rows[product] = new ShowConsumptionRowCommand()
                    command.rows[product].command = command
                    command.rows[product].product = product
                    command.rows[product].pricePerUnit = userHasFinanceRole ? product?.pricePerUnit : 0
                }

                // Keep track of quantity out based on transaction type
                if (transaction.transactionType.id == Constants.TRANSFER_OUT_TRANSACTION_TYPE_ID) {
                    command.rows[product].transferOutQuantity += transactionEntry.quantity
                    command.rows[product].transferOutTransactions << transaction

                    // Initialize transfer out by location map
                    if(transaction.destination && transaction.destination != transaction.source) {
                        def transferOutQuantity = command.rows[product].transferOutMap[transaction.destination]

                        if (!transferOutQuantity) {
                            command.rows[product].transferOutMap[transaction.destination] = 0
                        }

                        command.rows[product].transferOutMap[transaction.destination] += transactionEntry.quantity
                    }

                    def isFromPutawayOrder = transaction?.outgoingShipment?.isFromPutawayOrder
                    def isFromTransferOrder = transaction?.outgoingShipment?.isFromTransferOrder
                    def isInternalTransfer = isFromPutawayOrder || isFromTransferOrder
                    def isFromReturnOrder = transaction?.outgoingShipment?.isFromReturnOrder

                    if (isFromReturnOrder || !isInternalTransfer) {
                        command.rows[product].issuedQuantity += transactionEntry.quantity
                    }
                } else if (transaction.transactionType.id == Constants.EXPIRATION_TRANSACTION_TYPE_ID) {
                    command.rows[product].expiredQuantity += transactionEntry.quantity
                    command.rows[product].expiredTransactions << transaction
                } else if (transaction.transactionType.id == Constants.DAMAGE_TRANSACTION_TYPE_ID) {
                    command.rows[product].damagedQuantity += transactionEntry.quantity
                    command.rows[product].damagedTransactions << transaction
                } else if (transaction.transactionType.id == Constants.TRANSFER_IN_TRANSACTION_TYPE_ID) {
                    command.rows[product].transferInQuantity += transactionEntry.quantity
                    command.rows[product].transferInTransactions << transaction

                    // Initialize transfer out by location map
                    def transferInQuantity = command.rows[product].transferInMap[transaction.source]
                    if (!transferInQuantity) {
                        command.rows[product].transferInMap[transaction.source] = 0
                    }

                    if(transaction?.incomingShipment?.isFromReturnOrder) {
                        command.rows[product].returnedQuantity += transactionEntry.quantity
                    }

                    // Add to the total transfer out per location
                    command.rows[product].transferInMap[transaction.source] += transactionEntry.quantity

                } else if (transaction.transactionType.id == Constants.CONSUMPTION_TRANSACTION_TYPE_ID) {
                    command.rows[product].consumedQuantity += transactionEntry.quantity
                }

                command.rows[product].totalConsumptionQuantity = command.rows[product].issuedQuantity + command.rows[product].consumedQuantity - command.rows[product].returnedQuantity

                String dateKey = transaction.transactionDate.format("yyyy-MM")
                command.selectedDates.add(dateKey)

                // Capture month breakdown for all debits and credits
                if (transaction.transactionType.transactionCode == TransactionCode.DEBIT) {
                    // Add to total transfer out by month (initialize transfer out by month map)

grails-app/views/consumption/_filters.gsp
<%@ page import="org.pih.warehouse.core.Constants" %>
<style>
.chosen-container-multi .chosen-choices li.search-field input[type="text"] {
    height: 26px;
    line-height: 26px;
}

.location-container {
    height: 120px;
}

.location-container .chosen-container-multi .chosen-choices {
    height: 120px !important;
    overflow-y: auto;
}
</style>
<div class="filters">
	<g:form method="get" controller="consumption" action="show">

        <g:hiddenField name="parametersHash" value="${command?.generateParametersHash()}"/>

        <div class="box">
            <h2><warehouse:message code="consumption.parameters.label" default="Parameters"/></h2>

            <div class="parameters">

                <div class="filter-list-item">
                    <label>
                        <warehouse:message code="consumption.fromLocations.label" default="Origin(s)"/>
                    </label>
                    <g:selectLocation name="fromLocations" value="${command?.fromLocations?.id?:session?.warehouse?.id}"
                                      multiple="true" class="chzn-select-deselect"
                                      activityCode="${org.pih.warehouse.core.ActivityCode.MANAGE_INVENTORY}"
                                      data-placeholder="${warehouse.message(code:'consumption.fromLocations.label', default:'Origins(s)')}"/>

                    <div class="fade">
                        <warehouse:message code="consumption.origin.note.label" default="NOTE: Using multiple Origin locations may provide inaccurate results" />
                    </div>
                </div>
                <div class="filter-list-item">
                    <label>
                        <warehouse:message code="consumption.afterDate.label" default="Consumed on or after"/>
                    </label>
                    <div>
                        <g:jqueryDatePicker id="fromDate" name="fromDate" value="${command?.fromDate}" format="MM/dd/yyyy" cssClass="large" autocomplete="off"/>
                    </div>
                </div>
                <div class="filter-list-item">
                    <label>
                        <warehouse:message code="consumption.beforeDate.label" default="Consumed on or before"/>
                    </label>
                    <div>
                        <g:jqueryDatePicker id="toDate" name="toDate" value="${command?.toDate}" format="MM/dd/yyyy" cssClass="large" autocomplete="off"/>
                    </div>
                </div>
            </div>

            <h2><warehouse:message code="default.filters.label" default="Filters"/></h2>
            <div class="filters">

                <div class="filter-list">

                    <div class="filter-list-item">
                        <label>
                            <warehouse:message code="categories.label" default="Categories"/>
                        </label>
                        <g:selectCategory
                            name="selectedCategories"
                            multiple="true"
                            value="${command?.selectedCategories?.id}"
                            class="chzn-select-deselect"
                            data-placeholder="${g.message(code: 'default.selectOptions.label', default: 'Select Options')}"
                        />
                    </div>
                    <div class="filter-list-item">
                        <label>
                            <warehouse:message code="tags.label" default="Tags"/>
                        </label>
                        <g:selectTags
                            name="selectedTags"
                            value="${command?.selectedTags?.id}"
                            multiple="true"
                            class="chzn-select-deselect"
                            data-placeholder="${g.message(code: 'default.selectOptions.label', default: 'Select Options')}"
                        />
                    </div>
                    <g:if test="${!command?.toLocations}">
                        <div class="filter-list-item">
                            <label>
                                <warehouse:message code="consumption.toLocations.label" default="Destinations(s)"/>
                            </label>
                            <div class="location-container">
                                <g:selectLocation
                                    name="selectedLocations"
                                    value="${command?.selectedLocations?.id}"
                                    multiple="true"
                                    class="chzn-select-deselect"
                                    data-placeholder="${g.message(code: 'default.selectOptions.label', default: 'Select Options')}"
                                />
                            </div>

                            <span class="fade"><g:message code="consumption.destinations.optional.message"/></span>
                        </div>
                    </g:if>
                    <g:elseif test="${command?.toLocations}">
                        <div class="filter-list-item">
                            <label>
                                <warehouse:message code="consumption.toLocations.label" default="Destination(s)"/>
                            </label>
                            <div class="location-container">
                                <g:selectLocationWithOptGroup name="selectedLocations" from="${command?.toLocations}"
                                                              value="${command.selectedLocations*.id}"
                                                              class="chzn-select-deselect" multiple="multiple"/>
                            </div>
                        </div>
                    </g:elseif>
                </div>
            </div>
            <h2><warehouse:message code="consumption.renderOptions.label" default="Render Options"/></h2>
            <div class="options">

                <div class="filter-list-item">
                    <label><warehouse:message code="consumption.additionalColumns.label" default="Additional columns (CSV only)"/></label>
                    <select
                        name="selectedProperties"
                        multiple="true"
                        class="chzn-select-deselect"
                        data-placeholder="${g.message(code: 'default.selectOptions.label', default: 'Select Options')}"
                    >

                        <g:hasRoleFinance>
                            <g:set var="hasRoleFinance" value="${true}"/>
                        </g:hasRoleFinance>
                        <g:each var="property" in="${command.productDomain.properties}">
                            <g:if test="${!property.isAssociation() && property.typePropertyName != 'object'}">
                                <g:set var="disabled" value="${'pricePerUnit'.equals(property?.name) && !hasRoleFinance}"/>
                                <option value="${property.name}"
                                    ${command.selectedProperties?.toList()?.contains(property.name)?'selected':''}
                                    ${disabled?'disabled':''}>
                                    ${property.naturalName} (${property.typePropertyName})
                                </option>
                            </g:if>
                        </g:each>
                    </select>
                </div>
                <div class="filter-list-item">
                    <label>
                        <warehouse:message code="consumption.format.label" default="Format"/>
                    </label>
                    <div>
                        <label>
                            <g:radio name="format" value="html" checked="${params.format=='html'||!params.format}"/>
                            <warehouse:message code="default.html.label" default="HTML" />
                        </label>
                        <label>
                            <g:radio name="format" value="csv" checked="${false}" />
                            <warehouse:message code="default.csv.label" default="CSV" />
                        </label>
                    </div>
                </div>
                <div class="filter-list-item">
                    <label>
                        <warehouse:message code="default.options.label" default="Options"/>
                    </label>
                    <div class="checkbox">
                        <g:checkBox name="includeQuantityOnHand" value="${command.includeQuantityOnHand}"/>
                        <label for="includeQuantityOnHand">
                            <warehouse:message code="consumption.includeQuantityOnHand.label" default="Include quantity on hand"/>
                        </label>
                    </div>
                    <div class="checkbox">
                        <g:checkBox name="includeLocationBreakdown" value="${command.includeLocationBreakdown}"/>
                        <label for="includeLocationBreakdown">
                            <warehouse:message code="consumption.includeLocationBreakdown.label" default="Include location breakdown in CSV"/>
                        </label>
                    </div>
                    <div class="checkbox">
                        <g:checkBox name="includeMonthlyBreakdown" value="${command.includeMonthlyBreakdown}"/>
                        <label for="includeMonthlyBreakdown">
                            <warehouse:message code="consumption.includeMonthlyBreakdown.label" default="Include monthly breakdown in CSV"/>
                        </label>
                    </div>
                </div>
            </div>
            <div class="filter-list-item">
                <div class="buttons">
                    <button class="button">
                        <img src="${createLinkTo(dir:'images/icons/silk',file:'cog_go.png')}" />
                        <warehouse:message code="report.runReport.label" default="Run Report"/>
                    </button>

                    <g:link controller="consumption" action="show" class="button">
                        <img src="${createLinkTo(dir:'images/icons/silk',file: 'arrow_refresh.png')}" />
                        ${warehouse.message(code:'default.button.reset.label', default: 'Reset')}
                    </g:link>
                </div>
            </div>
        </div>
    </g:form>

</div>

grails-app/views/consumption/list.gsp
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="custom" />
        
        <title><g:message code="inventory.consumption.label"/></title>
        <link rel="stylesheet" href="${createLinkTo(dir:'js/pivottable/',file:'pivot.css')}" type="text/css" media="all" />
    </head>

	<body>
		<div class="body">
			<g:if test="${flash.message}">
				<div class="message">${flash.message}</div>
			</g:if>

            <div class="summary">
                <p class="title"><g:message code="inventory.consumption.label"/></p>

            </div>

            <div class="button-bar">
                <g:link controller="consumption" action="list" class="button">
                    <img src="${resource(dir:'images/icons/silk',file:'report.png')}" style="vertical-align: middle"/>
                    <warehouse:message code="consumption.report.show.label" default="Show Consumption Report"/>
                </g:link>
				<g:link controller="consumption" action="pivot" class="button">
					<img src="${resource(dir:'images/icons/silk',file:'report_edit.png')}" style="vertical-align: middle"/>
					<warehouse:message code="consumption.report.edit.label" default="Edit Consumption Report"/>
				</g:link>

                <g:isSuperuser>
                    <div class="right">
                        <g:link controller="consumption" action="refresh" class="button">
                            <img src="${resource(dir:'images/icons/silk',file:'table_refresh.png')}" />
                            <warehouse:message code="consumption.refreshData.label"/>
                        </g:link>
                    </div>
                </g:isSuperuser>

            </div>

            <div class="yui-gf">
                <div class="yui-u first">

                    <div class="box">
                        <h2><g:message code="default.filters.label"/></h2>

                        <g:form action="list" method="get">
                            <div class="filter-list-item">
                                        <label>${g.message(code: 'location.label')}</label>
                                        <g:selectDepot id="location" class="chzn-select-deselect filter"
                                                       name="location" noSelection="['':'']"
                                                       value="${command?.location?.id?:session?.warehouse?.id}"/>
                            </div>
                            <div class="filter-list-item">
                                        <label>${g.message(code: 'category.label')}</label>
                                        <g:selectCategory id="category" class="chzn-select-deselect filter"
                                                          name="category" noSelection="['':'']"
                                                          value="${command?.category?.id}"
                                        />
                            </div>
                            <div class="filter-list-item">
                                        <label>${g.message(code: 'consumption.startDate.label')}</label>
                                        <g:jqueryDatePicker
                                                id="startDate"
                                                name="startDate"
                                                cssClass="large"
                                                changeMonthAndYear="true"
                                                size="20"
                                                value="${command?.startDate }"
                                                format="MM/dd/yyyy"
                                                showTrigger="false"
                                        />
                            </div>
                            <div class="filter-list-item">
                                        <label>${g.message(code: 'consumption.endDate.label')}</label>
                                        <g:jqueryDatePicker
                                                id="endDate"
                                                name="endDate"
                                                cssClass="large"
                                                changeMonthAndYear="true"
                                                size="20"
                                                value="${command?.endDate }"
                                                format="MM/dd/yyyy"
                                                showTrigger="true"
                                        />
                            </div>
                            <div class="filter-list-item">

                                    <button id="btn-execute" name="execute" class="button">
                                        <img src="${resource(dir: 'images/icons/silk', file: 'zoom.png')}"/>
                                        &nbsp;<warehouse:message code="default.button.view.label"/> </button>

                                    <button id="btn-download" name="download" class="button" value="true">
                                        <img src="${resource(dir: 'images/icons/silk', file: 'page_excel.png')}"/>
                                        &nbsp;<warehouse:message code="default.button.download.label"/></button>

                                    <g:link controller="consumption" action="list" class="button">
                                        <img src="${resource(dir: 'images/icons/silk', file: 'arrow_refresh_small.png')}"/>
                                        <g:message code="default.button.clear.label"/>
                                    </g:link>

                            </div>
                        </g:form>
                    </div>
                </div>


                <div class="yui-u">
                    <div class="box">
                        <h2><g:message code="consumption.label"/></h2>
                        <div class="list dialog">
                            <div id="results">
                            </div>

                        </div>
                    </div>
                </div>
            </div>

		</div>
    %{--<script src="${createLinkTo(dir:'js/pivottable', file:'pivot.js')}" type="text/javascript" ></script>--}%
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/pivot.min.js" type="text/javascript" ></script>


    <script type="text/javascript">
        var utils = $.pivotUtilities;
        var sum = $.pivotUtilities.aggregatorTemplates.sum;
        var average = $.pivotUtilities.aggregatorTemplates.average;
        var numberFormat = $.pivotUtilities.numberFormat;
        var intFormat = numberFormat({digitsAfterDecimal: 0});

        $("#btn-execute").click(function(event) {
            event.preventDefault();
            refreshPivotTable()
        });

        $(".filter").change(function(event) {
            refreshPivotTable()
        });

        function refreshPivotTable() {
            var location = $("#location").val();
            var category = $("#category").val();
            var startDate = $("#startDate").val();
            var endDate = $("#endDate").val();
            drawPivotTable(location, category, startDate, endDate);
        }


        function drawPivotTable(location, category, startDate, endDate) {

            // Display loading message
            $("#results").html("<div class=\"loading\">Loading...</div>");

            // Get consumption data
            $.getJSON('${request.contextPath}/consumption/aggregate', {
                location: location,
                category: category,
                startDate: startDate,
                endDate: endDate
            }, function (data) {
                $("#results").pivot(
                    data, {
                        rows: ["productName"],
                        cols: ["year", "month"],
                        aggregator: sum(intFormat)(["quantity"])
                    });
            }).fail(function(xhr, textStatus, error) {
                console.log(xhr, textStatus, error);
                $("#results").html("An unexpected error has occurred").addClass("error")
            });
        }
        refreshPivotTable()

    </script>

	</body>

</html>

grails-app/views/consumption/pivot.gsp
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="layout" content="custom" />

    <title><g:message code="inventory.consumption.label"/></title>
    <link rel="stylesheet" href="${createLinkTo(dir:'js/pivottable/',file:'pivot.css')}" type="text/css" media="all" />

</head>

<body>
<div class="body">
    <g:if test="${flash.message}">
        <div class="message">${flash.message}</div>
    </g:if>

    <div class="button-bar">
        <g:link controller="consumption" action="list" class="button">
            <img src="${resource(dir:'images/icons/silk',file:'report.png')}" style="vertical-align: middle"/>
            <warehouse:message code="consumption.report.show.label" default="Show Consumption Report"/>
        </g:link>
        <g:link controller="consumption" action="pivot" class="button">
            <img src="${resource(dir:'images/icons/silk',file:'report_edit.png')}" style="vertical-align: middle"/>
            <warehouse:message code="consumption.report.edit.label" default="Edit Consumption Report"/>
        </g:link>
        <div class="right">
            <g:link controller="consumption" action="refresh" class="button">
                <img src="${resource(dir:'images/icons/silk',file:'table_refresh.png')}" style="vertical-align: middle"/>
                <warehouse:message code="consumption.refreshData.label"/>
            </g:link>
        </div>

    </div>

    <div class="box">
        <h2><g:message code="consumption.label"/></h2>
        <div id="output">
            <div class="loading">Loading...</div>

        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/pivot.min.js" type="text/javascript" ></script>


<script type="text/javascript">
    var utils = $.pivotUtilities;
    var sum = $.pivotUtilities.aggregatorTemplates.sum;
    var numberFormat = $.pivotUtilities.numberFormat;
    var intFormat = numberFormat({digitsAfterDecimal: 0});
    var renderers = $.extend(
        $.pivotUtilities.renderers,
        $.pivotUtilities.c3_renderers,
        $.pivotUtilities.d3_renderers,
        $.pivotUtilities.export_renderers
    );
    $.getJSON('${request.contextPath}/consumption/aggregate', {}, function(data) {
        $("#output").pivotUI(data, {
            cols: ["year", "month"],
            rows: ["productName"],
            aggregator: sum(["quantity"]),
            hiddenAttributes: [],
            renderers: renderers
        }, true);
    });


</script>

</body>

</html>