grails-app/controllers/org/pih/warehouse/data/DataExportController.groovy
/**
* Copyright (c) 2012 Partners In Health.  All rights reserved.
* The use and distribution terms for this software are covered by the
* Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
* which can be found in the file epl-v10.html at the root of this distribution.
* By using this software in any fashion, you are agreeing to be bound by
* the terms of this license.
* You must not remove this notice, or any other, from this software.
**/
package org.pih.warehouse.data

import grails.converters.JSON
import org.pih.warehouse.core.Document
import org.pih.warehouse.core.DocumentCode
import org.pih.warehouse.core.DocumentType

import java.nio.charset.Charset

class DataExportController {

    def dataService
    def index = {
        List<Document> documents = Document.findAllByDocumentCode(DocumentCode.DATA_EXPORT)
        [documents: documents]
    }

    def render = {
        Document document = Document.get(params.id)
        String query = new String(document.fileContents, Charset.defaultCharset());
        if (query) {
            def data = dataService.executeQuery(query)
            if (params.format == "csv") {
                String csv = dataService.generateCsv(data)
                response.setHeader("Content-disposition", "attachment; filename=\"${document.name}.csv\"")
                render(contentType: "text/csv", text: csv.toString(), encoding: "UTF-8")
                return
            }
            render dataService.executeQuery(query) as JSON
            return
        }
        render document as JSON

    }

}

grails-app/views/dataExport/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="custom"/>
    <title><warehouse:message code="default.dataExports.label" default="Data Exports"/></title>
</head>

<body>
<div role="main" class="body">
    <g:if test="${flash.message}">
        <div class="message">${flash.message}</div>
    </g:if>
    <g:if test="${flash.error}">
        <div class="error">${flash.error}</div>
    </g:if>
    <div class="button-bar">
    </div>

    <div class="yui-ga">
        <div class="yui-u first">
            <div class="box">
                <h2><warehouse:message code="default.dataExports.label" default="Data Exports"/></h2>
                <table>
                    <g:each in="${documents}" var="document">
                        <tr>
                            <td class="middle">
                                ${document.name}
                            </td>
                            <td class="right">
                                <g:link controller="dataExport" action="render" id="${document.id}" params="[format:'csv']" class="button">
                                    <img src="${createLinkTo(dir:'images/icons/silk',file:'page_excel.png')}" class="middle"/>&nbsp; CSV
                                </g:link>
                                <g:link controller="dataExport" action="render" id="${document.id}" params="[format:'json']" class="button">
                                    <img src="${createLinkTo(dir:'images/icons/silk',file:'page_code.png')}" class="middle"/>&nbsp; JSON
                                </g:link>
                            </td>
                        </tr>
                    </g:each>
                </table>
            </div>
        </div>
    </div>

</div>
</body>
</html>